export const ToolbarItems = [
  "undo",
  "redo",
  "save",
  "format_bold",
  "format_italic",
  "format_color_text",
  "format_color_fill",
  "format_underlined",
  "strikethrough_s",
  "border_all",
  "format_align_center",
  "vertical_align_bottom",
  "format_text_wrap",
];
